name: 功能建议
description: 建议一个适合小规模开源健康管理的改进
title: '[建议] '
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: 使用场景
      description: 你在什么情况下遇到什么问题？
    validations:
      required: true
  - type: textarea
    attributes:
      label: 建议方案
    validations:
      required: true
